# circos.conf

<<include etc/colors_fonts_patterns.conf>>
<<include ./ideogram.conf>>
<<include ./ticks.conf>>

<image>
angle_offset* = -82
<<include etc/image.conf>>
</image>
karyotype = ./karyotype.txt
chromosomes_units           = 1000000
chromosomes_display_default = yes


<plots>
<plot>
file       = ./plot_1.txt
max_gap    = 1u
color      = grey
min        = 1
max        = 12
r0         = 0.95r
r1         = 0.92r
thickness  = 2
fill_color = dblue
type       = histogram
</plot>

<plot>
file       = ./plot_2.txt
color   = spectral-7-div
scale_log_base = 0.6
max_gap = 1u
min     = 0
max     = 100000
r0         = 0.84r
r1         = 0.81r
type       = heatmap
</plot>
</plots>

<links>
<link>

file          = ./links.txt
color         = red
thickness     = 5
ribbon           = yes
flat             = yes
z      = 0
radius = 0.63r
bezier_radius = 0.4r
</link>

</links>





# Debugging, I/O an dother system parameters
# Included from Circos distribution.
<<include etc/housekeeping.conf>>




