# circos.conf

<<include etc/colors_fonts_patterns.conf>>
<<include ./ideogram.conf>>
<<include ./ticks.conf>>

<image>
angle_offset* = -82
<<include etc/image.conf>>
</image>

# Karyotype — chemin relatif depuis config/
karyotype = ../results/karyotype.txt

chromosomes_units           = 1000000
chromosomes_display_default = yes

<plots>

# Heatmap densité TE — palette orange (chaud = beaucoup de TE)
<plot>
type           = heatmap
file           = ../results/TE_density.txt
r0             = 0.88r
r1             = 0.95r
min            = 17000
max            = 100000
color          = orrd-9-seq
scale_log_base = 0.5
</plot>

# Heatmap densité gènes — palette bleue (foncé = beaucoup de gènes)
<plot>
type           = heatmap
file           = ../results/gene_density.txt
r0             = 0.79r
r1             = 0.87r
min            = 0
max            = 16
color          = blues-9-seq
</plot>

# Histogramme nombre moyen d'exons — bleu acier
<plot>
type       = histogram
file       = ../results/nb_exons.txt
r0         = 0.70r
r1         = 0.78r
min        = 3
max        = 16
color      = dblue
fill_under = yes
fill_color = lblue
thickness  = 0
max_gap    = 1u
</plot>

# Histogramme longueur moyenne des exons — bleu ciel
<plot>
type       = histogram
file       = ../results/len_exons.txt
r0         = 0.61r
r1         = 0.69r
min        = 200
max        = 600
color      = blue
fill_under = yes
fill_color = vlblue
thickness  = 0
max_gap    = 1u
</plot>

</plots>

<links>
<link>
file          = ../results/links.txt
color         = red_a4
thickness     = 2
ribbon        = yes
flat          = yes
z             = 0
radius        = 0.56r
bezier_radius = 0.4r
</link>
</links>

<<include etc/housekeeping.conf>>
