#IDEOGRAM.CONF


<ideogram>

<spacing>

default = 0.01r
break   = 2u
<pairwise HG2-2 HG1-1>
spacing = 2r
</pairwise>
</spacing>

<<include ./ideogram.position.conf>>
<<include ./ideogram.label.conf>>
<<include ./bands.conf>>

</ideogram>
