#IDEOGRAM.LABEL.CONF

show_label     = yes
label_font     = condensedbold
label_radius   = dims(ideogram,radius) + 0.1r
label_center   = yes
label_size     = 50
label_with_tag = yes
label_parallel = yes
label_case     = upper